
for i in xrange(1000):
	a = 10
	a = a - 1
	a = a * a
	a = 10
	a = a - 1
	a = a * a
	a = 10
	a = a - 1
	a = a * a
	a = 10
	a = a - 1
	a = a * a
	a = 10
	a = a - 1
	a = a * a
	a = 10
	a = a - 1
	a = a * a
	a = 10
	a = a - 1
	a = a * a
	a = 10
	a = a - 1
	a = a * a
	a = 10
	a = a - 1
	a = a * a
	# sphere0.transform.position = Vector3(Mathf.Sin(timer), Mathf.Cos(timer), 0)
	# sphere1.transform.position = Vector3(Mathf.Sin(timer), Mathf.Cos(timer), 1)
	# sphere2.transform.position = Vector3(Mathf.Sin(timer), Mathf.Cos(timer), 2)
	# sphere3.transform.position = Vector3(Mathf.Sin(timer), Mathf.Cos(timer), 3)
	# sphere4.transform.position = Vector3(Mathf.Sin(timer), Mathf.Cos(timer), 4)
	# sphere5.transform.position = Vector3(Mathf.Sin(timer), Mathf.Cos(timer), 5)
	# sphere6.transform.position = Vector3(Mathf.Sin(timer), Mathf.Cos(timer), 6)
	# sphere7.transform.position = Vector3(Mathf.Sin(timer), Mathf.Cos(timer), 7)
	# sphere8.transform.position = Vector3(Mathf.Sin(timer), Mathf.Cos(timer), 8)
	# sphere9.transform.position = Vector3(Mathf.Sin(timer), Mathf.Cos(timer), 9)
	# sphere10.transform.position = Vector3(Mathf.Sin(timer), Mathf.Cos(timer), 10)
	# sphere11.transform.position = Vector3(Mathf.Sin(timer), Mathf.Cos(timer), 11)
	# sphere12.transform.position = Vector3(Mathf.Sin(timer), Mathf.Cos(timer), 12)
	# sphere13.transform.position = Vector3(Mathf.Sin(timer), Mathf.Cos(timer), 13)
	# sphere14.transform.position = Vector3(Mathf.Sin(timer), Mathf.Cos(timer), 14)
	# sphere15.transform.position = Vector3(Mathf.Sin(timer), Mathf.Cos(timer), 15)
	# sphere16.transform.position = Vector3(Mathf.Sin(timer), Mathf.Cos(timer), 16)
	# sphere17.transform.position = Vector3(Mathf.Sin(timer), Mathf.Cos(timer), 17)
	# sphere18.transform.position = Vector3(Mathf.Sin(timer), Mathf.Cos(timer), 18)
	# sphere19.transform.position = Vector3(Mathf.Sin(timer), Mathf.Cos(timer), 19)
